import type { NextRequest } from "next/server"
import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx"

export async function GET(_req: NextRequest, { params }: { params: { filename: string } }) {
  const { filename } = params

  // Build a minimal Word document
  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            text: "Generated Charter Party",
            heading: HeadingLevel.TITLE,
          }),
          new Paragraph({
            children: [
              new TextRun("This is a preview document generated by the Smart CP Generator (Next.js preview)."),
            ],
          }),
          new Paragraph({
            text: "",
          }),
          new Paragraph({
            text: "Note: In the original Flask app, a model compares Base CP and Recap to produce replacements.",
          }),
          new Paragraph({
            text: "For this live preview, we’re returning a sample file so you can test the full flow end-to-end.",
          }),
        ],
      },
    ],
  })

  const buffer = await Packer.toBuffer(doc)

  return new Response(buffer, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-cache",
    },
  })
}
